AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3BucketOne:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      DeletionPolicy: Retain
      Tags:
        owner-email: "mdbf42@gmail.com"
  S3BucketTwo:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      DeletionPolicy: Retain
      Tags:
        owner-email: "mdbf42@gmail.com"
  S3BucketThree:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      DeletionPolicy: Retain
      Tags:
        owner-email: "mdbf42@gmail.com"